{{- if .Values.enabled }}
{{- if .Values.operator }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.operator.namespace | default "openshift-operators" }}
spec:
  channel: {{ .Values.operator.channel }}
  installPlanApproval: {{ .Values.operator.installPlanApproval }}
  name: {{ .Values.operator.name }}
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.operator.version | quote }}
{{- end }}
{{- end }}